#!/bin/bash
set -e

exec > >(sudo tee /var/log/user-data.log) 2>&1
echo "Starting user-data script at $(date)"

cd /home/admin

# -------------------------------------------------------------------
# 1. Set environment variables
# -------------------------------------------------------------------
ENV_FILE="/etc/environment"

if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.backup"
fi

%{ for env_var in app_env ~}
sed -i '/^${env_var.key}=/d' "$ENV_FILE" 2>/dev/null || true
%{ endfor ~}

%{ for env_var in app_env ~}
echo "${env_var.key}=${replace(env_var.value, "'", "'\\''")}" >> "$ENV_FILE"
%{ endfor ~}

PROFILE_SCRIPT="/etc/profile.d/pulse-alerts-cron-env.sh"
cat > "$PROFILE_SCRIPT" << 'PROFILE_HEADER'
# Pulse Alerts Cron environment variables
# Automatically generated by user-data script
PROFILE_HEADER

%{ for env_var in app_env ~}
echo "export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'" >> "$PROFILE_SCRIPT"
%{ endfor ~}

chmod 644 "$PROFILE_SCRIPT"

%{ for env_var in app_env ~}
export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'
%{ endfor ~}

# -------------------------------------------------------------------
# 2. Install Java 17
# -------------------------------------------------------------------
echo "Installing Java 17 JRE..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y openjdk-17-jre-headless curl unzip

export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin
java -version

# -------------------------------------------------------------------
# 3. Download artifact from CodeArtifact
# -------------------------------------------------------------------
AWS_REGION="ap-south-1"
CODEARTIFACT_DOMAIN="pulse-prod"
CODEARTIFACT_REPOSITORY="pulse-alerts-cron"
APPLICATION_NAME="pulse-alerts-cron"
VERSION=${artifact_version}

echo "Downloading $APPLICATION_NAME version $VERSION from CodeArtifact..."
aws codeartifact get-package-version-asset \
  --region "$AWS_REGION" \
  --domain "$CODEARTIFACT_DOMAIN" \
  --repository "$CODEARTIFACT_REPOSITORY" \
  --format generic \
  --namespace "pulse" \
  --package "$APPLICATION_NAME" \
  --package-version "$VERSION" \
  --asset "$APPLICATION_NAME-$VERSION.zip" \
  "$APPLICATION_NAME.zip"

# -------------------------------------------------------------------
# 4. Unzip and verify artifact
# -------------------------------------------------------------------
unzip "$APPLICATION_NAME.zip"

if [ ! -f "$APPLICATION_NAME/pulse-alerts-cron.jar" ]; then
    echo "ERROR: JAR file not found at $APPLICATION_NAME/pulse-alerts-cron.jar"
    exit 1
fi

# -------------------------------------------------------------------
# 5. Create systemd service for persistence across reboots
# -------------------------------------------------------------------
APP_DIR="/home/admin/$APPLICATION_NAME"

cat > /etc/systemd/system/pulse-alerts-cron.service << EOF
[Unit]
Description=Pulse Alerts Cron Service
After=network.target

[Service]
Type=simple
User=admin
WorkingDirectory=$APP_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$JAVA_HOME/bin/java -jar $APP_DIR/pulse-alerts-cron.jar run org.dreamhorizon.pulsealertscron.verticle.MainVerticle
Restart=on-failure
RestartSec=10
StandardOutput=append:/var/log/pulse-alerts-cron.log
StandardError=append:/var/log/pulse-alerts-cron.log

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable pulse-alerts-cron
systemctl start pulse-alerts-cron

# -------------------------------------------------------------------
# 6. Verify the service started
# -------------------------------------------------------------------
sleep 10

if systemctl is-active --quiet pulse-alerts-cron; then
    echo "pulse-alerts-cron started successfully"
else
    echo "WARNING: pulse-alerts-cron may not have started properly"
    journalctl -u pulse-alerts-cron --no-pager -n 50 || true
fi

echo "User-data script completed at $(date)"
echo "Service managed by: systemctl {start|stop|restart|status} pulse-alerts-cron"
echo "Logs: journalctl -u pulse-alerts-cron -f  OR  /var/log/pulse-alerts-cron.log"
